version: '3.5'

services:
  api:
    container_name: basenodejs
    image: basenodejs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    links:
      - postgres_db
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:9.6.17-alpine
    container_name: "postgres_db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: codemanday   
      PGDATA: /data/postgres   
    ports:
      - 5432:5432
volumes:
    postgres_database:
        external: true